---
title: "My GitHub Space"
author: "Alanna Kaiser"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: haddock
    number_sections: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  revealjs::revealjs_presentation:
    fig_height: 4
    highlight: haddock
    reveal_options:
      chalkboard:
        theme: chalkboard
        toggleChalkboardButton: yes
        toggleNotesButton: yes
      previewLinks: yes
      progress: yes
      slideNumber: yes
    reveal_plugins:
    - chalkboard
    - zoom
    self_contained: no
    theme: solarized
    transition: convex
  bookdown::epub_book: default  
  bookdown::gitbook:
    highlight: haddock
    css: styles.css
    config:
      download:
      - introduction-to-R.pdf
      - introduction-to-R.epub
  tint::tintPdf:
    highlight: haddock
    number_sections: yes
    toc: yes
  radix::radix_article:
    toc: true
    toc_depth: 2
  pagedown::html_paged: 
    highlight: haddock
    toc: yes
    number_sections: yes
    theme: default
  tint::tintHtml:
    highlight: haddock
    number_sections: yes
    toc: yes
  tufte::tufte_handout:
    fig_height: 2.5
    toc: yes
    number_sections: yes
    latex_engine: xelatex
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About Me

My name is Alanna Kaiser and I am an MSW candidate at the University of Michigan. In U-M's social work program, I am concentrating my studies in Social Policy and Evaluation, with a particular interest in communities and social systems. I have professional experience working in education, housing, and community-based development and neighborhood revitalization.  

### Current Work

This summer, I am working as a Measurement and Evaluation intern with Habitat for Humanity Greater San Francisco. In this role, I am specifically conducting research and implementing a program evaluation to aid the Neighborhood Revitalization (NR) and Homeowner Development Departments (HDD), respectively.  With NR, I am compiling evidence to support Habitat’s work in green space improvement in the Bayview Neighborhood of San Francisco. With HDD, I am conducting an internal evaluation to map the lifecycles of each program, highlighting key stages, accompanying process documentation, and stakeholders engaged. 


## My Portfolio

In the coming weeks, I will add content to this online space that showcases my growing data visualization and analysis skills. The following is a small sampling of that work:

* [SW670: Final Portfolio](https://alannakz.github.io/DataViz2019/Winter_Portfolio.html)
* [Homework Challenge 6/3/19- Samples of Data Manipulation](https://alannakz.github.io/DataViz2019/HomeworkChallengeRMD.html)
* [Fun With Mapping 6/6/2019](https://alannakz.github.io/DataViz2019/Mapping.html) 
* [Other samples of work]

## My Blog Posts

*Blog posts are forthcoming



